logging:
  level:
    root: INFO
    com.barbosa: DEBUG

server:
  port: 8080

spring:
  application:
    name: infinitecore-commerce

  banner:
    location: classpath:banner.txt

  datasource:
    url: jdbc:postgresql://localhost:5432/infinitecore
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
